name = "apa-v1"
compatibility_date = "2026-05-14"
pages_build_output_dir = "kiosk/dist"

[[d1_databases]]
binding = "APA_LOGS_DB"
database_name = "apa_voice_logs"
database_id = "5e65d679-2c00-4ef8-915d-803494b34f96"
